# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_profile', '0003_auto_20180801_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='area_of_interest',
        ),
        migrations.AddField(
            model_name='mentee',
            name='areas_of_guidance',
            field=models.CharField(choices=[('portfolio code reviews', 'Portfolio / Code Reviews'), ('job search and interviews', 'Job Search and Interviews'), ('industry trends skills technologies', 'Industry Trends, Skills, Technologies'), ('leadership management', 'Leadership, Management'), ('business entrepreneurship', 'Business, Entrepreneurship'), ('career growth', 'Career Growth')], default='unknown', max_length=30),
        ),
    ]
