# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_profile', '0004_auto_20180807_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='areas_of_guidance',
            field=models.CharField(choices=[('portfolio code reviews', 'Portfolio / Code Reviews'), ('job search and interviews', 'Job Search and Interviews'), ('industry trends skills tech', 'Industry Trends, Skills, Technologies'), ('leadership management', 'Leadership, Management'), ('business entrepreneurship', 'Business, Entrepreneurship'), ('career growth', 'Career Growth')], default='unknown', max_length=30),
        ),
    ]
